### PR TITLE
"('stuff'.equal? 'stuff').should == false" cannot be supported on Opal

### PR DESCRIPTION
**Pull request by vais**
Ref https://github.com/opal/opal/pull/730

### CODE REVIEW

**Comment by vais** [comment]
@elia I saw you merged my other PR to Opal rubyspec fork, but you are not merging this one, which leads me to believe you are still undecided whether `('stuff'.equal? 'stuff').should == false` can be made to work on Opal?

My understanding of the issue is this: since Opal already made the decision that mutable strings will not be supported, and this being just another side of the same coin, `('stuff'.equal? 'stuff').should == false` is an impossible proposition in Opal.

**Comment by elia** [comment]
No, I just don't have much time with a newborn around, and I prefer to merge stuff when I'm sure I understood what's going on and I'm ok with the change. Deciding whether I'm ok it's the result of having time and understanding the change of course. 

(right now writing while having breakfast ☕️) :D

**Comment by vais** [comment]
@elia Funny, I will soon be joining the club :) Maybe that's why I'm trying to get as much done as I can in the next few months :) Thanks for taking the time for Opal despite your crazy schedule, I really appreciate everything you do to keep this project moving forward.

**Comment by vais** [comment]
@elia please pardon my cluelessness, but how do I see this change to rubyspec in my opal fork? Both my opal/opal and opal/rubyspec forks are even with upstream master, but I think the submodule in opal/opal is still pointed to an older commit in opal/rubyspec. Is this something I can resolve on my end, or do you need to do something in opal/opal for everyone to start seeing the latest commit to opal/rubyspec from their opal/opal rubyspec submodule?

**Comment by elia** [comment]
@vais no problem! you `cd` to `spec/corelib` and update the submodule repo, via `pull` (or fetch + reset hard or whatever), then you'll find that the containing opal repo has an uncommitted change and you can `git add spec/corelib` and `git commit` as usual. If you wanna push a PR after that I'll merge it promptly ;)

(Congratz for the upcoming birth!)

**Comment by vais** [comment]
I see now, I was getting confused about the fact that this would also have to be another PR to opal/opal afterwards. Thanks @elia!

**Pull request merged**
