### PR TITLE
Missing case: "/[]9999".succ should be "/[]10000"

### PR DESCRIPTION
**Pull request by vais**
I would have preferred to send this PR to [rubyspec/rubyspec](https://github.com/rubyspec/rubyspec), but that project is dead?

### CODE REVIEW

**Comment by elia** [comment]
I wonder how the @jruby guys are handling this, whether they stopped using rubyspec or forked (as we're doing) and if it could make sense to have a shared fork…

cc @headius @adambeynon @meh

**Comment by vais** [comment]
@elia totally. Because having multiple independent forks is the absolute worst thing that could possibly have come out of @brixen's decision to close down rubyspec. Huge :+1: for an official fork shared by all implementations!

**Comment by Ajedi32** [comment]
Based on the [network graph](https://github.com/rubyspec/rubyspec/network), it looks like the most mature fork of Rubyspec right now is [ruby/rubyspec](https://github.com/ruby/rubyspec). And apparently [they accept pull requests](https://github.com/ruby/rubyspec#do-you-receive-pull-requests).

**Comment by vais** [comment]
@Ajedi32 looks good! @elia what do you think? And what would it take to get Opal to switch to using ruby/rubyspec? Pardon my ignorance, I have no clue how much rubyspec has been modified for Opal...

**Comment by Ajedi32** [comment]
> Pardon my ignorance, I have no clue how much rubyspec has been modified for Opal...

Don't worry, [the network graph](https://github.com/opal/rubyspec/network) can solve that problem too! :wink: Looks like this fork is only 3 commits ahead of (and quite a few commits behind) rubyspec/rubyspec.

**Comment by vais** [comment]
Thanks, @Ajedi32! @elia, so that's it, these are all the changes: https://github.com/rubyspec/rubyspec/compare/master...opal:master

**Comment by headius** [comment]
Perhaps it's worth expressing (to ruby-core) an interest in having ruby/rubyspec become a canonical fork?

**Comment by vais** [comment]
@headius makes sense, doesn't it? :+1:

**Comment by elia** [comment]
@headius anything I can do to help expressing that interest?

**Comment by Ajedi32** [comment]
@elia Couldn't we just start sending pull requests to that repo? Their README currently says:

> # Do you receive pull requests?
>
> Yes. If the pull request won't break anything, it will be merged.

So we could just start submitting them there, and if the project maintainers have any objections then the pull request in question would be a great place to have that kind of discussion IMO.

**Comment by headius** [comment]
I would definitely recommend starting by submitting pull requests to @nurse's repo. We'll sort out the proper home for it later.

**Comment by Ajedi32** [comment]
@headius Nurse? :confused: You mean ruby/rubyspec?

**Comment by headius** [comment]
@Ajedi32 Yes, sorry, I forgot it had moved :-)

**Comment by elia** [comment]
https://github.com/opal/opal/pull/886 to the rescue!

**Pull request merged**
